### ISSUE TITLE
fooof.synth: gen_group_power_spectrum() gives error on empty gaussian params

### ISSUE THREAD

**Issue by ArcadeShrimp** [fooof-tools/fooof#115]
Given empty gauss params `gauss = []` gen_group_power_spectra() halts and output and IndexError

**Code Snippet**
![fooof_empty_gauss_errors](https://user-images.githubusercontent.com/14008089/49246231-3b14e000-f3c9-11e8-9059-17e7139b5995.PNG)

**Comment by TomDonoghue** [comment]
Note: I think this is a consequence of an update to the input checking from when I 'fixed' some input handling when we updated `_check_iter` (update was for dealing with n=2 or 3 cases). 

ToDo: update _check_iter to explicitly deal with an empty list, as it should.
