### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by LeilaNS** [fooof-tools/fooof#120]
Hi,
I have installed fooof, but I cann't use it, do you know what's wrong?:
**$ pip install fooof**
_/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
 warnings.warn(warning, RequestsDependencyWarning)
Requirement already satisfied: fooof in ./.local/lib/python2.7/site-packages (0.1.2)
Requirement already satisfied: scipy>=0.19.0 in ./.local/lib/python2.7/site-packages (from fooof) (1.1.0)
Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages (from fooof) (1.15.4)_

 **In [1]: from fooof import FOOOF**
  
  _File "/home/user/.local/lib/python2.7/site-packages/fooof/fit.py", line 683
    lo_bound = [bound if bound[0] > self.freq_range[0] else [self.freq_range[0], *bound[1:]] for bound in lo_bound]
                                                                                 ^
SyntaxError: invalid syntax_

**Comment by danieltomasz** [comment]
fooof requires Python >= 3.5  to run, you are using  Python 2.7

**Comment by LeilaNS** [comment]
Python 3.5 have been installed in my workspace
**$ which python3.5**
_/usr/bin/python3.5_

**Comment by danieltomasz** [comment]
Are you using Ubuntu or other linux distribution? Try then `pip3 install fooof`
From your output it seems you are trying to install `fooof` with python2 
What is the output of `pip --version`?

You may also try `python3.5 -m pip install fooof`

**Comment by LeilaNS** [comment]
python3.5 -m pip install fooof works,
Thanks

**Comment by TomDonoghue** [comment]
Thanks a lot for helping with this @danieltomasz ! Glad you got it fixed @LeilaNS
