### ISSUE TITLE
Terminology: Amplitude vs Power

### ISSUE THREAD

**Issue by TomDonoghue** [fooof-tools/fooof#131]
We refer to the 'amplitude' of peaks variously through the tutorials and codebase, but I think this is the wrong term, right? Size of the peaks is in the same units as the input power spectrum, so should always be referred to as units of power (unless I'm missing / misunderstanding something).

**Comment by voytek** [comment]
Yes, the expected input is a PSD, so you're correct that we should be talking about "power". _That said_, I've already encountered people fooof'ing non-PSDs that have similar properties. So maybe a note at the beginning of the tutorials saying "we designed this to take in power spectra, and will therefore refer to 'power' throughout, but the actual units depend on the inputs given."
