### ISSUE TITLE
FOOOFGroup knee setting

### ISSUE THREAD

**Issue by marco-matta96** [fooof-tools/fooof#144]
How to include the 'knee' parameter when fitting with FOOOFGroup?

**Comment by TomDonoghue** [comment]
It has the same setting inputs as the FOOOF object!

So, if you're on the current version from pip, it's:
`FOOOFGroup(background_mode='knee')`

If you have the newest version, from Github, the name has changed:
`FOOOFGroup(aperiodic_mode='knee')`

**Comment by TomDonoghue** [comment]
@marco-matta96 : did you get every you need working? Also just a general note that there are a lot of examples and descriptions on the FOOOF documentation website: https://fooof-tools.github.io/fooof/

If everything is good, then we can close this issue!

**Comment by marco-matta96** [comment]
Yes it is! Thank you
