### ISSUE TITLE
Tutorial 02: Causes confusion

### ISSUE THREAD

**Issue by LJGz** [fooof-tools/fooof#149]
As an introduction to the toolbox the first tutorial may cause confusion for new users who are unfamiliar with Python.

https://fooof-tools.github.io/fooof/auto_tutorials/plot_02-FOOOF.html#sphx-glr-auto-tutorials-plot-02-fooof-py does not make it clear where to locate the files below if they have used pip to install. 
```
freqs = np.load('dat/freqs.npy')
spectrum = np.load('dat/spectrum.npy')
```
This results in a confusing error for those new to python and to workaround requires the user to locate the files on GitHub and set the location of the downloaded files, which is not an intuitive step. These files may exist in the pip install but its not clear where to find them.

Once that issue is resolved by the user the output of 
```
fm.report(freqs, spectrum, freq_range)
```
contains **Background Parameters** instead of **Aperiodic Parameters**
Which causes further confusion and errors for the user when following the tutorial and attempting to run
```
print('Aperiodic parameters: \n', fm.aperiodic_params_, '\n')
```
producing the output

> Attribute error: 'FOOOF' object has no attribute 'aperiodic_params_'

**Comment by TomDonoghue** [comment]
Hey @LJGz - sorry for the very delayed response! 

You are totally correct about these issues. 

In terms of the differences in naming, that was a mismatch between versions. That should hopefully all be addressed now - with the release of the new version (on pre-release) and update of the site. 

For downloading the data, that's actually still slightly tricky, as we are not currently packaging that data with the pip install. You can run these things as normal if you clone the repo, but can't super easily download these files from the website and get running. I'll need to think about if there is an easy way to get that data, and/or at least add some better notes to the tutorials that use it.

**Comment by danieltomasz** [comment]
> For downloading the data, that's actually still slightly tricky, as we are not currently packaging that data with the pip install. You can run these things as normal if you clone the repo, but can't super easily download these files from the website and get running. I'll need to think about if there is an easy way to get that data, and/or at least add some better notes to the tutorials that use it.

Hey @TomDonoghue  maybe you could use similar way the mne handle the tutorial data 
- or simply check: if data doesn't exist on path  maybe use 'urllib.request.urlretrieve' from the standard library to   download the file from github

**Comment by TomDonoghue** [comment]
@danieltomasz 

It was on my ToDo list to look into how MNE do their data handing, and so on, though I wasn't sure if we needed quite as much as what they have. 

As a simple solution, I really like the suggestion of using `urllib.request.urlretrieve` to grab files as needed - I tried it out and it seems to work, so it is now PR'd in #164.

Thanks a lot for the suggestion! I'm glad this turned into a clean and straightforward solution!

**Comment by TomDonoghue** [comment]
The download data utilities and approach, and updates to the tutorials, are now merged to master. 

Thanks for the notes and recommendations here! I'm going to close this issue now.
