### ISSUE TITLE
Separate out an 'ideas' or 'dev' repo

### ISSUE THREAD

**Issue by TomDonoghue** [fooof-tools/fooof#154]
There are quite a few issues open here, like #30 or #47, that are sorta still open, but are not software or code questions per se, but more like open research questions than code issues. 

I think it might make sense, now that FOOOF 1.0 is largely a settled tool to somewhat separate out 'FOOOF as a research question' from 'FOOOF as a software tool'. So basically, I'm thinking we start a 'dev-ideas' or something repo on the org here, that can be a place to talk about new ideas for the project (in the research sense), but in a way that leaves this repo and it's issue board for code and user questions. 

tl-dr : I want to move some old issues, that aren't really code related, to a different place. 

Asking: @voytek @rdgao

**Comment by rdgao** [comment]
sounds good to me

**Comment by voytek** [comment]
Ditto. This makes sense.

**Comment by TomDonoghue** [comment]
Okay, done, and relevant issues moved over. 

The new repository for discussion of FOOOF developmen ideas is here:
https://github.com/fooof-tools/Dev-Ideas
