### ISSUE TITLE
Guess value for knee value

### ISSUE THREAD

**Issue by TomDonoghue** [fooof-tools/fooof#156]
After checking through #82, I updated FOOOF to use a data derived guess value for the exponent starting parameter. This doesn't seem to matter, in practice, but avoids a magic number. 

Which raises the question - we still use a guess parameter for the knee parameter. It's set at zero, for no particular reason. Is there any better guess parameter for the knee, and/or any way to data derive a guess?

This is basically a question for @rdgao

**Comment by rdgao** [comment]
empirically, a small (non-zero) number might be better, like 10 or something. I doubt this makes a difference either, and maybe 10 feels more magic than 0 so we might just want to keep 0.

In other words, I have no idea. But maybe this is a good place to try to solve the problem where a knee is fit when there isn't necessarily one (at least in the range of the data)?

**Comment by TomDonoghue** [comment]
Okay cool - so based on the notion that 10 is not practically different from 0 (this seems true in some really quick checks) but 10 is somehow 'more magic' than 0, then I'm going to leave it at 0. 

My quick checks do suggest really big differences in knee guess value can affect the outcome (but otherwise it doesn't matter too much). 

I also agree this is something that can be collapsed into some work looking into knee fitting more generally - but I'd say that is more of a development question, and so I'm moving that whole discussion here:
https://github.com/fooof-tools/Development/issues/7
