### ISSUE TITLE
documentation: FOOOFgroup has empty attributes peak_params_ and aperiod_params_

### ISSUE THREAD

**Issue by nschawor** [fooof-tools/fooof#160]
These attributes are of NoneType and not a 2d/1d arrays as stated in object documentation (as the fitted parameters are contained in group_results). Also, more verbose object description could be helpful, as discussed in lab meeting. 

```python
import fooof
import fooof.sim

n_spectra = 10
freq_range = [3, 100]
ap_params = [0.5, 1]
gauss_params = [10, 0.4, 1]
nlv = 0.02

# Synthesize a group of power spectra
freq, psd, _ = fooof.sim.gen_group_power_spectra(n_spectra, freq_range,
                    ap_params, gauss_params, nlv)

fm = fooof.FOOOFGroup()
fm.fit(freq, psd)
print(type(fm.peak_params_))  #NoneType
```

**Comment by TomDonoghue** [comment]
I'm somewhat unclear what the 'bug' is here. `peak_params_`, etc, hold individual model results. An individual model is undefined in a Group object (so, None), and all results are collected into `group_results`. 

If it's just documentation, what's the documentation you would suggest? This could perhaps be noted more clearly in the object docstring, though the usecase here is (I think) covered in the tutorial.

**Comment by nschawor** [comment]
No bug, only documentation/clarity.
If these attributes are always empty, maybe they should be removed from the top-level FOOOFGroup object along with the corresponding attribute descriptions for the FOOOFGroup object?

**Comment by TomDonoghue** [comment]
Yeh - so the FOOOFGroup object which inherits from FOOOF, programmatically copies the documentation of FOOOF, and then adds some things to the end. This copies a lot of docs that are strictly true, but not exactly useful to FOOOFGroup in practice.

I think it might make more sense to scrap the doc copy, and just update the FOOOFGroup docs to note the specific attributes of FOOOFGroup, that are relevant (with perhaps a note that it does have the FOOOF attributes but these are used internally and not useful in the same way).

**Comment by TomDonoghue** [comment]
Okay, I changed how the docs get copied, and added a more specific docstring to the FOOOFGroup object, which surfaces the use of the `power_spectra` and `group_results` attributes, and downplays all the others (they are mentioned in a note at the end). This should hopefully be a clearer documentation on the FOOOFGroup object.

Updated added to #152 

I'm going to close this now - @nschawor if you have any more notes suggestions about this topic, or feel something else / more should be done re the changes, then feel free to re-open it.
