### ISSUE TITLE
 Background Parameters

### ISSUE THREAD

**Issue by LeilaNS** [fooof-tools/fooof#161]
Hi,
I would like to get and save Background Parameters (1 of f slope), for each sensor, what I should do?
Thanks,

**Comment by TomDonoghue** [comment]
Hey @LeilaNS - it's a little hard to answer super specifically without knowing more about the data / analysis. 

There is a lot of info in the tutorials to guide various use cases:
https://fooof-tools.github.io/fooof/auto_tutorials/index.html

For example, the FOOOFGroup tutorial covers how to run FOOOF across a matrix of power spectra. If this is a matrix of power spectra across channels, then you can get all the exponents by doing:
`fg.get_params('aperiodic_params', 'exponent')`
