### ISSUE TITLE
AttributeError: 'FOOOFGroup' object has no attribute 'get_params'

### ISSUE THREAD

**Issue by LeilaNS** [fooof-tools/fooof#162]
Hi,
I use FOOOFGroup:
fg = FOOOFGroup(peak_width_limits=[1, 8], min_peak_height=0.05, max_n_peaks=6)
fg.fit(freqs, spectra)
[out] Running FOOOFGroup across 52 power spectra.
I can plot the results but when I tried to extract the fit parameters:
 aps = fg.get_params('aperiodic_params')
 I got this error : 
Traceback (most recent call last):
  File "<ipython-input-99-5a3385411a6a>", line 1, in <module>
  aps = fg.get_params('aperiodic_params')
AttributeError: 'FOOOFGroup' object has no attribute 'get_params
I updatet my fooof liberary, but I got the same error.
Could yoou please help me?
Thanks

**Comment by TomDonoghue** [comment]
Hey @LeilaNS:

Sorry for the delay! Sorry that there has been a disconnect between the website and the code - things fell out of sync for a bit as we were in the midst of updating things. 

If you are still using FOOOF, what I recommend now is that you can update to the newest version which is on pre-release (instructions to get it in the README), and the site has also been updated, and so everything should be consistent and working from there!

**Comment by TomDonoghue** [comment]
Hopefully the new site layout and release have fixed these issues, so I'm going to close this issue now - but feel free to re-open / ask any more questions if you have them!
