### ISSUE TITLE
AttributeError: 'FOOOF' object has no attribute '_aperiodic_params_'

### ISSUE THREAD

**Issue by rakansha** [fooof-tools/fooof#163]
I used fooof to fit my power spectrum:
```
fmBaecC4 = FOOOF()
fmBaecC4.fit(powBfreq,powBaec[:,5], freq_range)
fmBaecC4.peak_params_
fmBaecC4.error_
fmBaecC4.r_squared_
fmBaecC4.aperiodic_params_
```
while I do get the response for the first 3 parameters I extract, the last one gives the following error:

> AttributeError: 'FOOOF' object has no attribute 'aperiodic_params_'

I don't get what might be causing the issue here

**Comment by rakansha** [comment]
As opposed to the tuitorial, using 
`fmBaecC4.background_params_`
gave the required output
I found the solution here : https://gitmemory.com/LJGz

**Comment by TomDonoghue** [comment]
Hey @rakansha:

Sorry for the delay - you are totally right that there was an issue and disconnect between the documentation site and the public codebase, as we we're in the midst of putting out an update. 

I'm glad you found the answer, that `aperiodic_params` used to be called `background_params` in the older code version. If you want to update to the new version of the code, there are instructions in the README, and the website has also been updated again, to bring things together to the new version. 

Feel free to re-open this if anything comes up - but for now I'm going to close this issue.
