### ISSUE TITLE
FOOOF Warning: Lower-bound peak width limit is < or ~= the frequency resolution

### ISSUE THREAD

**Issue by rakansha** [fooof-tools/fooof#165]
I am fitting my power spectrum with the following parameters:
1. frequency = 1.17 to 100 with a frequency resolution of 0.39 Hz
2. power spectrum-corresponding to 1 above
3. freq range=[2 40]
I don't quite understand why I receive the warning

> FOOOF WARNING: Lower-bound peak width limit is < or ~= the frequency resolution: 0.39 <= 0.50
	Lower bounds below frequency-resolution have no effect (effective lower bound is freq-res)
	Too low a limit may lead to overfitting noise as small bandwidth peaks.
	We recommend a lower bound of approximately 2x the frequency resolution.

Is there any additional parameter I need to add?

**Comment by TomDonoghue** [comment]
Information on the settings for FOOOF are all described here:
https://fooof-tools.github.io/fooof/auto_tutorials/plot_04-MoreFOOOF.html#sphx-glr-auto-tutorials-plot-04-morefooof-py

Let me know if you have any questions that aren't covered by the tutorial.

**Comment by TomDonoghue** [comment]
Feel free to re-open this is you have any other questions / follow ups - but otherwise I'm going to close this for now!
