### ISSUE TITLE
ModuleNotFoundError: No module named 'fooof.analysis.error'; 'fooof.analysis' is not a package

### ISSUE THREAD

**Issue by rakansha** [fooof-tools/fooof#166]
Hi!
I uninstalled my previous version of fooof and installed it again using pip in Anaconda terminal. I was importing relevant libraries

`import numpy as np
from fooof import FOOOF, FOOOFGroup
import matplotlib.pyplot as plt
import scipy.io as spio
from fooof.analysis.error import compute_pointwise_error_fm, compute_pointwise_error_fg
`

I get the error

> ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-fe9527df7e1c> in <module>
      5 import matplotlib.pyplot as plt
      6 import scipy.io as spio
----> 7 from fooof.analysis.error import compute_pointwise_error_fm, compute_pointwise_error_fg

ModuleNotFoundError: No module named 'fooof.analysis.error'; 'fooof.analysis' is not a package

>

**Comment by TomDonoghue** [comment]
Did you install the pre-release version? You'll need that version, meaning you need to install from pip as:
`pip install fooof --pre`

You'll probably need to uninstall again first.

**Comment by rakansha** [comment]
Hey,
I uninstalled fooof and  installed the pre-version , it works now
Thanks

**Comment by TomDonoghue** [comment]
Awesome, glad it's working!
