### ISSUE TITLE
FOOOFGroup Report plots swap Knee and Exponent labels

### ISSUE THREAD

**Issue by D1o0g9s** [fooof-tools/fooof#209]
The axis labels are swapped for knee and exponent in the FOOOFGroup summary plots. Should swap Knee and Exponent axis labels to make consistent with data. 

Lines affecting this: 
https://github.com/fooof-tools/fooof/blob/c7b77eade15df504b84d4e5372db7c2b04f519f6/fooof/plts/fg.py#L82-L85

Sample screenshot:
<img width="791" alt="Screen Shot 2021-04-26 at 9 40 29 PM" src="https://user-images.githubusercontent.com/6126624/116186381-5e4a3380-a6d8-11eb-8472-0b3213bae92f.png">

**Comment by TomDonoghue** [comment]
Thanks catching this @D1o0g9s! 

This has now been fixed in #210 by @ryanhammonds, so I'll close this now.
