### ISSUE TITLE
[BUG] IndexError when plotting

### ISSUE THREAD

**Issue by ryanhammonds** [fooof-tools/fooof#211]
This issue is came up [here](https://github.com/nschawor/ieeg-spatial-filters-ssd/pull/1). Whenever no peaks are found and `plot_peaks='line'` is passed to the plot method of a fm, an IndexError is raised. It may be useful turn this error into a warning?

**Comment by TomDonoghue** [comment]
Is this still the case on main, or just 1.0.0? I think I fixed this recently. If it's still happening, then yeh, I don't think it should even be a warning, it should just proceed as normal, without annotating any peaks since there aren't any.

**Comment by ryanhammonds** [comment]
I tried from main too, and the same error was raised.

**Comment by TomDonoghue** [comment]
Ahh, it looks like I fixed it somewhere in #205 then, as this seems to work now on that branch. 

Just to double check - this is what I ran:
```
from specparam import PSD
from specparam.sim import gen_power_spectrum

freqs, pows = gen_power_spectrum([3, 40], [1, 1], [1, 1, 1])

fm = PSD(max_n_peaks=0)
fm.fit(freqs, pows)
fm.plot(plot_peaks='line')
```

Which (on `name`) runs, and spits out a plot with no annotated peaks (since there are none) and no warning or error. 
Does this seem like it addresses the error, and seem like good behaviour to you?

**Comment by ryanhammonds** [comment]
I was wrong and this is fixed on main too! I was getting an unrelated error from using `plot_style=None` which seems to be deprecated on main.

Since this is already fixed, I'll go ahead and close this.

**Comment by TomDonoghue** [comment]
Ahh, okay cool that makes sense! I think the `plot_style` is deprecated since #176 got merged. Anyways, glad it should be fixed now - thanks for checking through!
