### ISSUE TITLE
Interpreting negative knee frequency in aperiodic fit

### ISSUE THREAD

**Issue by AdityaNanda** [fooof-tools/fooof#213]
Hi there! Firstly, I wanted to thanks to the developers for the hard work in developing this tool. 

I am analyzing SEEG recordings from our lab.  I used resting state data, downsampled to Fs= 250 Hz and band pass filtered with [5, 125 ] Hz and filtered to remove line noise (at 60 Hz and harmonics). Spectra was computed using pwelch function. Then, I used FOOOFGroup (parameters as shown below)  to extract 'offset' ,'knee' and 'exponent' for each ROI.  I am only interested in the aperiodic fit.  The periodic parameters are not relevant to this work.

fg = FOOOFGroup(peak_width_limits=[0.5, 12], aperiodic_mode='knee')

All the exponents are  consistent with past literature ( ~ 2.5). However, some of the ROI's have a negative knee parameter (typically larger than -20 ). How do I interpret this negative parameter.  Is the knee parameter required to be postiive? Shown below is the spectra and the fit for 1 of the ROIs.  

![fooof_debug](https://user-images.githubusercontent.com/45182225/124034004-45a01780-d9c0-11eb-828c-8fe1fde6656d.png)

Is this a legit fit or I am doing something wrong?  Should I change the peak_width_limits? Please let me know if you need more info.  Thanks

**Comment by ryanhammonds** [comment]
Hi @AdityaNanda, thanks a ton for the issue! Edge cases like this help us improve the software or documentation.

I agree that the negative knee param is odd as I have not encountered it before. I'm not sure how to interpret a negative knee but @TomDonoghue likely has more insight into this.

Would you possibly be able to share the fit+data for the example you show here? You could use `fm.save(file_name, save_results=True, save_settings=True, save_data=True)` which will a json file. You could also save out the freqs + powers as a .npy file. Working with this example will help me better understand what's going on - and to provide a clear explanation or a PR addressing this issue.

**Comment by AdityaNanda** [comment]
Hi Ryan, so I found a small bug in my preprocessing for ephys timeseries.  I fixed the bug and rerun fooof and now I am getting knee values that are mostly positive (there are very few, small negative knee values  ~ - 0.2 ).  Can these small negative knee values be attributed to numerical errors ?   I am certainly not getting large negative values (for instance, -30, in the plot above )

I have attached the json file for a single set of spectra. Please let me know if it is not correctly saved.  
[test.zip](https://github.com/fooof-tools/fooof/files/6773077/test.zip)

**Comment by ryanhammonds** [comment]
Hi @AdityaNanda, thanks for sharing the data. It looks like the zip was for the FOOOFGroup objects. However, no fits return negative knee values:

```python
from fooof import FOOOFGroup

fg = FOOOFGroup()

fg.load('test.json', '/home/voytek/projects/fooof')

fg.get_params('aperiodic', 'knee').min()
```
> 8.071986044101514

What version of fooof are you using? You can check with `pip freeze | grep fooof` from a terminal, or with:
```python
import fooof
fooof.__version__
```

**Comment by TomDonoghue** [comment]
Hey @AdityaNanda - I just wanted to drop in some quick notes on what I do know about negative knees - though to be honest, it's a bit of a mystery! Basically, it makes sense to me that negative knees are likely to be non-physiological (in that I don't think they are expected physiologically). It could be that some kind of noise, and/or reaching the noise floor of the recording system leads to a plateauing in the higher frequencies, which leads to an upward bend and negative knee. This might relate to what you've found with fixing the processing getting rid of at least most of the negative knees. 

If you are currently getting some knees that are small values (near zero), it seems likely to me that these are perhaps just slightly noisy estimations of models that perhaps have no knee (approximately zero), and it's not clear they should be interpreted as _true_ negative knee values. 

Somewhat related: I don't think it really explains whats happening here, but I see that there is a notch filter at the line noise frequency, and this "missing power" can sometimes "pull off" the model fit a bit. In general, it can be useful to interpolate away this dip to help the model fit. 

Also, thanks @ryanhammonds for helping to look into this and checking out the data. I'll let you two continue poking at the actual data, but please tag me back in if y'all have any more Qs that I might be able to help with!
