### ISSUE TITLE
Extracting aperiodic fit from FOOOF object. Previously called  _bg_fit (version 0.3.1)

### ISSUE THREAD

**Issue by QuirinevEngen** [fooof-tools/fooof#214]
Hi! 

As a dedicated fooof/specparam user I have one feedback:
I remember when using 0.3.1 version that I could easily extract the aperiodic fit from the model and use that for plotting using "_bg_fit". However, with the 1.0.0 version, that doesn't seem to be an attribute anymore. Which means I have to use "gen_aperiodic", which seems a bit redundant.

For my case in specific, I already have my notebooks ready from the previous version, but now I need to change half of that code to retrieve the aperiodic fit. 

Is it easy to bring that attribute back in the new version? I think future users might also benefit from this.

Kind regards,
Quirine

**Comment by TomDonoghue** [comment]
What used to called `_bg_fit` is still there - it's just that it's called `_ap_fit` now!

In the name change the general label "background (bg)" got changed to "aperiodic (ap)", but otherwise, nothing should have been removed!

**Comment by QuirinevEngen** [comment]
Thanks! This is a life saver! I was looking all over in the documentation, but it makes sense I couldn't find it, because it's a hidden variable.

**Comment by TomDonoghue** [comment]
Yeh - the individual model components are not documented... but maybe they should be, as I think people do use them a fair bit. An example on the website that describes and explore the individual components (and how to regenerate each one) might be useful. 

Also, general python thing I use a lot - the `dir` function displays all attributes of an object, for example:
`dir(fm)`. 
Even I forget the exact name of things a bunch, but this (and/or tab complete) can help check and explore what's available on an object.
