### ISSUE TITLE
fooof makes no plot, but run without error

### ISSUE THREAD

**Issue by reihanehk** [fooof-tools/fooof#229]
Hi,
I am new to using fooof. I start with tutorials. So I used this example:  https://fooof-tools.github.io/fooof/auto_tutorials/plot_01-ModelDescription.html#sphx-glr-auto-tutorials-plot-01-modeldescription-py

The program runs without error. The problem is that it does not produce any output, I mean plots. 
The code just runs without error, but no plots generate. 

I use python3.7

It is very kind of you if you can help me.
Bests,
Reihaneh

**Comment by danieltomasz** [comment]
hi @reihanehk could you post what  after what exact lines did get the error  and what exactly error message says?

**Comment by reihanehk** [comment]
Dear Daniel,
I use "gedit" as an editor, so I simply create a file.py and write in it.

About matplotlib: How to use matplotlib to show? I first import matplotlib:

import matplotlib
import matplotlib.pyplot as plt

and then after the plot line I add the imshow command:
plot_spectrum(freqs1, powers1, log_powers=True,color='black',
label='Original Spectrum')
plt.imshow(plot_spectrum)

The error corresponds to this, is as follows:
"TypeError: Image data of dtype object cannot be converted to float"

Then I changed the show to:
plt.imshow(freqs1, powers1, log_powers=True,color='black', label='Original
Spectrum')
And got the error:

raise ValueError(msg)
ValueError: array([3.33133997, 2.85348927, 2.53017744, 2.19036401,
2.0175487 ,
       1.78397516, 1.66730339, 1.54839588, 1.48514765, 1.41887019,
       1.41075459, 1.49554666, 1.58140191, 1.59754655, 1.59756898,
       1.44941714, 1.27247376, 1.09128643, 0.93335946, 0.85207351,
       0.779784  , 0.73907346, 0.71248964, 0.67455575, 0.65553159,
       0.64690398, 0.62965521, 0.61203596, 0.58510124, 0.57603363,
       0.5656749 , 0.54792493, 0.5179963 , 0.5026074 , 0.50232429,
       0.49484643, 0.4760664 , 0.47026464, 0.45588201, 0.44572864,
       0.43659996, 0.42736487, 0.41623501, 0.42022426, 0.41044135,
       0.40050152, 0.40169906, 0.40177931, 0.41661601, 0.4189917 ,
       0.43868748, 0.4593224 , 0.4707363 , 0.4769046 , 0.46448783,
       0.4622835 , 0.43685863, 0.41834885, 0.38410281, 0.36744251,
       0.34061184, 0.32443924, 0.30680238, 0.29653995, 0.28879739,
       0.28720717, 0.27741212, 0.27408775, 0.27413941, 0.26833627,
       0.26240819, 0.26060482, 0.2523007 , 0.24880516, 0.25125349]) is not
a valid value for name; supported values are 'Accent', 'Accent_r', 'Blues',
'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap',
'CMRmap_r', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r', 'Greens', 'Greens_r',
'Greys', 'Greys_r', 'OrRd', 'OrRd_r', 'Oranges', 'Oranges_r', 'PRGn',
'PRGn_r', 'Paired', 'Paired_r', 'Pastel1', 'Pastel1_r', 'Pastel2',
'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn', 'PuBuGn_r', 'PuBu_r',
'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples', 'Purples_r', 'RdBu',
'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu', 'RdYlBu_r',
'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r', 'Set2', 'Set2_r',
'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia', 'Wistia_r', 'YlGn',
'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r', 'YlOrRd', 'YlOrRd_r',
'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'binary', 'binary_r', 'bone',
'bone_r', 'brg', 'brg_r', 'bwr', 'bwr_r', 'cividis', 'cividis_r', 'cool',
'cool_r', 'coolwarm', 'coolwarm_r', 'copper', 'copper_r', 'cubehelix',
'cubehelix_r', 'flag', 'flag_r', 'gist_earth', 'gist_earth_r', 'gist_gray',
'gist_gray_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r',
'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r',
'gist_yarg', 'gist_yarg_r', 'gnuplot', 'gnuplot2', 'gnuplot2_r',
'gnuplot_r', 'gray', 'gray_r', 'hot', 'hot_r', 'hsv', 'hsv_r', 'inferno',
'inferno_r', 'jet', 'jet_r', 'magma', 'magma_r', 'nipy_spectral',
'nipy_spectral_r', 'ocean', 'ocean_r', 'pink', 'pink_r', 'plasma',
'plasma_r', 'prism', 'prism_r', 'rainbow', 'rainbow_r', 'seismic',
'seismic_r', 'spring', 'spring_r', 'summer', 'summer_r', 'tab10',
'tab10_r', 'tab20', 'tab20_r', 'tab20b', 'tab20b_r', 'tab20c', 'tab20c_r',
'terrain', 'terrain_r', 'turbo', 'turbo_r', 'twilight', 'twilight_r',
'twilight_shifted', 'twilight_shifted_r', 'viridis', 'viridis_r', 'winter',
'winter_r'

**Comment by TomDonoghue** [comment]
Hey @reihanehk - based on the code you mention, I don't think this is anything to do with fooof plots, but simply about how to plot. Doing something like `plt.imshow(plot_spectrum)` isn't how the plotting works - if you are looking to explore how matplotlib works you might want to check out their documentation. 

Something like `plot_spectrum(freqs1, powers1)` should work. If the plot is not being shown, you might need to add `plt.show()` (whether you need this depends on the IDE / editor you are using.

**Comment by reihanehk** [comment]
@TomDonoghue Tons of thanks. To update:  I found the root of issue is matplotlib which has some conflicts with some of my python3.7 packages (to short, the main problem was tkinter). Therefore, I just used plt.savefig("file.png") and then got the plot as an output.

**Comment by TomDonoghue** [comment]
@reihanehk - sounds good, it seems this issue is therefore fixed! If so, I'm going to close this now, but you can re-open it if anything else needs addressing here.
