### ISSUE TITLE
Trouble downloading FOOOF to Ananconda 3 environment 

### ISSUE THREAD

**Issue by kkauraiims** [fooof-tools/fooof#233]
Hey all, I would be grateful if you could resolve this issue for me. 

I am using the conda command line to install FOOOF in my system: 

$ conda install -c conda-forge fooof

And somehow it is installing only in the Base environment, but not Ananconda3, which is creating downstream issues with MATLAB  wrapper (screenshot attached). I am suspecting this is the reason why FOOOF is not working for MATLAB since the 'pyenv' in MATLAB links to the ANACONDA3 files and not the base. 

Can someone help me out with this? 

<img width="1198" alt="Screenshot 2022-04-07 at 9 08 29 AM" src="https://user-images.githubusercontent.com/89849204/162170778-bc55e028-2fd4-4845-957d-89bd203be079.png">

**Comment by ryanhammonds** [comment]
Hi @kkauraiims, I think you need to activate the anaconda3 environment first, before installing fooof from conda forge:
```
$ conda activate anaconda3
$ conda install -c conda-forge fooof
```

**Comment by kkauraiims** [comment]
Thanks @ryanhammonds!! 
Unfortunately, I am getting bugs for both commands. 
The conda activate doesn't seem to be working, and while activating FOOOF I am getting warnings in the output code.  I have attached screenshots of both, any help in this regard would be useful, since I am not able to use FOOOF in MATLAB at all. 

<img width="499" alt="Screenshot 2022-04-12 at 8 47 17 AM" src="https://user-images.githubusercontent.com/89849204/162872705-6bc30a48-3d11-426c-bb08-4a21ca499337.png">

<img width="1059" alt="Screenshot 2022-04-13 at 10 39 49 AM" src="https://user-images.githubusercontent.com/89849204/163104655-9c66a729-8be4-46e5-b0ba-afe751ebe748.png">

**Comment by danieltomasz** [comment]
@kkauraiims I am not using anaconda but `pyenv` to create virtualenvs, but I think this is a more general problem how Matlab handles interaction with python, not related to fooof, maybe something from this page help you https://nl.mathworks.com/matlabcentral/answers/325435-python-api-setup-environments-how-to-get-matlab-to-use-other-env-as-interpeter
(basically you need to point Matlab to the specific virtual environment you installed fooof)

About creating conda env and the error you are getting , I think there something not right with the conda write right to folder you are installing fooof, check this disusssion https://stackoverflow.com/a/59750131You might need to change access rights to this folder

**Comment by TomDonoghue** [comment]
Hey @kkauraiims - since this is a question mostly about Anaconda environments (and old & likely to be outdated), I'm going to close this now. If you still have questions about getting fooof installed / running, feel free to comment / reopen, and we can try and help.
