### ISSUE TITLE
[ENH]: Show full PSD when plotting PSD+model using fm.plot()

### ISSUE THREAD

**Issue by moritz-gerster** [fooof-tools/fooof#245]
# Enhancement to improve FOOOF's plotting function for better visual inspection

## Current situation
The aperiodic component is often used in a narrow frequency range, for example, 30-50 Hz (Gao et al. 2017). 

When calling `fm.plot()`, the PSD and the fitted model are only shown in the fitting range (e.g. 30-50 Hz). However, to evaluate the fit visually, I find it essential to view the full PSD (e.g. 1-100 Hz). 

## Why not ideal
I emphasize the importance of this [with this code](https://github.com/fooof-tools/fooof/files/10030300/fooof_plotting_enh.pdf). For M/EEG researchers, the shown spectrum with the gigantic beta oscillation might look artificial. However, it actually perfectly resembles a true LFP signal obtained from a Parkinsonian subthalamic nucleus ([Gerster et al. 2022](https://doi.org/10.1007/s12021-022-09581-8)). When applying FOOOF and evaluating the fits, I was fooled into believing, that 30-45 Hz might be a good fit range for the aperiodic component (see the first figure provided by FOOOF). It took me some time plotting the full spectrum (second figure) to realize that I was actually fitting the beta peak instead of the aperiodic component! 

## Suggestion
I would suggest adding another keyword argument `freq_range` to `fm.plot(freq_range=None)`.

If `freq_range=None`, the plotted frequency range will be set to the fitting `freq_range=fit_range`, as currently. If `freq_range="full"`, the entire spectrum is plotted, and if `freq_range=(float1, float2)` the frequency range from float1 to float2 Hz will be plotted. 

It would be amazing to enable this keyword also in `fm.save_report()` as I usually check these reports to evaluate my fitting parameters.

**Comment by TomDonoghue** [comment]
Hey @moritz-gerster - thanks for the notes and the PR on this idea. 

The short story is that I agree on better support for the kind of checks that you want to do, but I am wary of the strategy of adding potentially a lot more data to be stored in the model objects (and potentially saved out). A key design goal of fooof is to be as efficient as possible (we have use cases fitting millions or billions of spectra now), and I would like to avoid adding / duplicating data in the object that isn't required for fitting. In general, I also think this is the kind of check that should be fully explored early on in the design of the analysis, but only some situations will have the kind of issue you mention, and once the analysis is set in, the broader range should not necessarily be needed anymore. 

With all that in mind - I explored a different strategy for addressing this in #276 that I think covers what you want this functionality to do, without adding the data to the object. Could you have a look at that PR and see if it addresses what you want out of this functionality?

By the way - I know some papers focus on something like 30-45 Hz, but it is not something I would recommend. This kind of narrow fitting regime is not something we show or recommend in the documentation, and is even [suggested against](https://fooof-tools.github.io/fooof/faq.html#what-frequency-range-should-the-model-be-fit-on). I personally think we should always be visualizing power spectra before fitting, and fitting as broad a range as we can.

**Comment by moritz-gerster** [comment]
Hi @TomDonoghue, Thanks for picking this up! Your points make a lot of sense and it seems you found a great solution in #276. Looks good from my side :)

**Comment by TomDonoghue** [comment]
Functionality for this is now merged in #276 - so closing this now!
