### ISSUE TITLE
Underfitting advice

### ISSUE THREAD

**Issue by scp010** [fooof-tools/fooof#250]
I have a fairly smooth power spectrum as shown below and there is a visual peak at 19Hz that the model is unable to identify due to the noise threshold. I have tried manipulating the fooof object parameters for peak height and threshold, but am unable to get the model to identify that peak. If anyone has any advice on fitting a more aggressive aperiodic noise model or other methods for identification, that would be very helpful, thanks!

![Figure 2023-02-07 115521](https://user-images.githubusercontent.com/57231905/217327064-2dbc726f-8ae4-4dd4-a1c5-ba84ef2f57a8.png)

**Comment by TomDonoghue** [comment]
Hey @scp010 - sorry for a delay in getting back to you here!

I agree that in this case the model looks to be somewhat underestimating the aperiodic exponent (we might want the blue line to be a bit steeper), and this seems related to not finding the small bumb at 19 Hz. Note that small peaks are difficult to detect and measure. 

If you have tried to tips and tricks described in the documentation (https://fooof-tools.github.io/fooof/), including exploring the different parameters, and perhaps tweaking the frequency range that you fit, then I think you are not missing anything here in terms of controlling how the model fit. It might just be that in this case the model can't quite fit the data in a way that catches this small peak. This can happen if the data doesn't quite follow the shape the model expects (in this case exact shape of the aperiodic component seems to be a bit different from what the model can fit).
