### ISSUE TITLE
Scaling / Y-axis units? 

### ISSUE THREAD

**Issue by SusanL82** [fooof-tools/fooof#255]
Hello, 

This is probably a silly question, but could you please tell me how the y-axis scaling of the model works? I've been searching through the functions, but I somehow keep overlooking it (I think). 

Because of some helpful reviewer comments, I am trying to get detect some additional peaks from previously Fooofed spectra. 
We originally ran a parametrization for the narrower, lower frequency peaks in our hippocampal LFPs (basically detecting delta and theta peaks) and got pretty good results. 
I now have to add peak detection for what is basically our gamma oscillation. The problem is that this is a very broadband oscillation, that our original models tried to solve by fitting multiple 12Hz-wide gaussians.  I cannot just re-run the analysis with settings for much wider peaks, because this throws the aperiodic fit way off and it then fails to detect our narrower peaks (basically, the entire lower frequency part of the spectrum ends up getting detected as a wide peak). 

So, what I am trying to do is basically this: 
1) reconstruct the aperiodic spectrum based on my previously obtained offset, knee and slope values
2) subtract that aperiodic spectrum from my original power spectrum
3) find my broadband peaks in the newly flattened spectrum

The problem is that my original spectrum and the aperiodic parameters are currently in different arbitrary units and I somehow can't find out how to scale them.

**Comment by TomDonoghue** [comment]
Hey @SusanL82 - sorry for the delay in getting back to you!

I'm not sure I fully understand the specifics of the question about the y-scaling of the model, but I'll add some quick notes and (if this is even still relavent), we can continue from there:
- while we take in linear power values, we immediately log (base 10) the power values, so the most literal answer is that the model y-values are in log10 scale
- this is the effective scaling of the model fit parameters, so the offset, exponent, peak height relate to y-values in log10 scale
- if you need to reconstruct model fits from learned parameters, you can do so by passing in the frequency vector and parameters to the relevant function (for example: https://github.com/fooof-tools/fooof/blob/main/fooof/objs/fit.py#L472)

**Comment by TomDonoghue** [comment]
Hey @SusanL82 - since there isn't an action item here, and the above hopefully answers the question, I'm going to close this issue now - but feel free to follow up if you have any comments / further questions!

**Comment by SusanL82** [comment]
Hi, thanks for the reply!
As it turns out, I had a problem with matlab log-axis scaling (ylim did not work the way I thought it did for semilog plots). My fooof outputs and reconstructed plots now match again.
