### ISSUE TITLE
Removing the pink noise

### ISSUE THREAD

**Issue by MZeydabadi** [fooof-tools/fooof#261]
Is it possible to remove the pink (1/f) noise from real EEG signals using the fooof package? If yes, could you provide an example?

**Comment by danieltomasz** [comment]
(I am not a developer) It is possible to use output from `specparam` to analyse EEG and then use custom code to remove 1/f  part of the signal (leaving aside the meaning of it, if it should be interpreted as a noise).

However, for you maybe it will be more straightforward to use another alogorithm (IRASA) provided in another python package, you could check it here https://github.com/raphaelvallat/yasa/blob/master/notebooks/09_IRASA.ipynb

**Comment by MZeydabadi** [comment]
> (I am not a developer) It is possible to use output from `specparam` to analyse EEG and then use custom code to remove 1/f part of the signal (leaving aside the meaning of it, if it should be interpreted as a noise).
> 
> However, for you maybe it will be more straightforward to use another alogorithm (IRASA) provided in another python package, you could check it here https://github.com/raphaelvallat/yasa/blob/master/notebooks/09_IRASA.ipynb

Thanks for the pointer but that [notebook](https://github.com/raphaelvallat/yasa/blob/master/notebooks/09_IRASA.ipynb) does not help either. From what I understand, the [notebook](https://github.com/raphaelvallat/yasa/blob/master/notebooks/09_IRASA.ipynb) provides you with a fit for the PSD of the 1/f component. How can I use that to remove the 1/f noise in the time-domain?

**Comment by TomDonoghue** [comment]
Hey @MZeydabadi - sorry for a delay in getting back to you on this!

If you mean does fooof provide a method to remove the 1/f component _in the time domain_, the answer is unfortunately, no. The fooof package operates in the frequency domain. 

You may be interested in looking into this paper, which proposes a way to remove 1/f components in the time domain:
https://www.sciencedirect.com/science/article/pii/S1053811922000581

**Comment by MZeydabadi** [comment]
Thanks for the pointer.

**Comment by TomDonoghue** [comment]
@MZeydabadi - no problem! Since this question is addressed, I'm going to close this issue now - but feel free to follow up with any more comments and/or open another issue if you have any further questions about fooof!
