### ISSUE TITLE
FOOOFGroup.plot() function breaks with numpy >= 1.24.0

### ISSUE THREAD

**Issue by sydney-smith** [fooof-tools/fooof#263]
New updates to numpy have caused the .plot() function for a FOOOFGroup object to break. 
Downgrading to 1.23.5 or earlier solves this problem. 

`import mne`
`from fooof import FOOOFGroup`

`eeg_path = '\path\'`
`eeg_dat = mne.io.read_raw_fif(eeg_path);`

`spectrum = eeg_dat.compute_psd(method='welch', fmin=0, fmax=100, n_fft=2000, n_overlap=1000)`
`freqs = spectrum.freqs`
`psds = spectrum.get_data()`

`fg = FOOOFGroup(peak_width_limits=[1, 8], min_peak_height=0.05, max_n_peaks=6)`
`fg.fit(freqs, psds, freq_range = [1,30])`

`fg.plot()`

The last line of code gives the following ValueError, causing the peak frequency histogram to fail. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 fg.plot()

File ~/opt/anaconda3/envs/test_fg/lib/python3.9/site-packages/fooof/objs/group.py:403, in FOOOFGroup.plot(self, save_fig, file_name, file_path)
    400 @copy_doc_func_to_method(plot_fg)
    401 def plot(self, save_fig=False, file_name=None, file_path=None):
--> 403     plot_fg(self, save_fig, file_name, file_path)

File ~/opt/anaconda3/envs/test_fg/lib/python3.9/site-packages/fooof/core/modutils.py:180, in check_dependency.<locals>.wrap.<locals>.wrapped_func(*args, **kwargs)
    177 if not dep:
    178     raise ImportError("Optional FOOOF dependency " + name + \
    179                       " is required for this functionality.")
--> 180 func(*args, **kwargs)

File ~/opt/anaconda3/envs/test_fg/lib/python3.9/site-packages/fooof/plts/fg.py:57, in plot_fg(fg, save_fig, file_name, file_path)
     55 # Center frequencies plot
     56 ax2 = plt.subplot(gs[1, :])
---> 57 plot_fg_peak_cens(fg, ax2)
     59 if save_fig:
     60     if not file_name:

File ~/opt/anaconda3/envs/test_fg/lib/python3.9/site-packages/fooof/core/modutils.py:180, in check_dependency.<locals>.wrap.<locals>.wrapped_func(*args, **kwargs)
    177 if not dep:
    178     raise ImportError("Optional FOOOF dependency " + name + \
    179                       " is required for this functionality.")
--> 180 func(*args, **kwargs)

File ~/opt/anaconda3/envs/test_fg/lib/python3.9/site-packages/fooof/plts/fg.py:114, in plot_fg_peak_cens(fg, ax)
    102 @check_dependency(plt, 'matplotlib')
    103 def plot_fg_peak_cens(fg, ax=None):
    104     """Plot peak center frequencies, in a histogram.
    105 
    106     Parameters
   (...)
    111         Figure axes upon which to plot.
    112     """
--> 114     plot_hist(fg.get_params('peak_params', 0)[:, 0], 'Center Frequency',
    115               'Peaks - Center Frequencies', x_lims=fg.freq_range, ax=ax)

File ~/opt/anaconda3/envs/test_fg/lib/python3.9/site-packages/fooof/objs/group.py:378, in FOOOFGroup.get_params(self, name, col)
    374 # Pull out the requested data field from the group data
    375 # As a special case, peak_params are pulled out in a way that appends
    376 #  an extra column, indicating which FOOOF run each peak comes from
    377 if name in ('peak_params', 'gaussian_params'):
--> 378     out = np.array([np.insert(getattr(data, name), 3, index, axis=1)
    379                     for index, data in enumerate(self.group_results)])
    380     # This updates index to grab selected column, and the last column
    381     #  This last column is the 'index' column (FOOOF object source)
    382     if col is not None:

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (60,) + inhomogeneous part.

**Comment by sydney-smith** [comment]
Also comes with this visible warning:

VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  out = np.array([np.insert(getattr(data, name), 3, index, axis=1)

**Comment by ryanhammonds** [comment]
This should be fixed on the main branch now.
