### ISSUE TITLE
Run modes

### ISSUE THREAD

**Issue by mwprestonjr** [fooof-tools/fooof#292]
FOOOFGroup.get_group() does not set the run modes (_debug, _check_freqs, _check_data) to match that of the input object, which can cause errors; while FOOOFGroup.get_fooof() sets the data mode only. Including "run_modes" as a key within the attributes dictionary returned by core/info/get_description() may facilitate tracking of these attributes. 
Also, _check_freqs is not included in the docstring of fit.py.

**Comment by TomDonoghue** [comment]
Ahhh, ooops, yes - good catch! I'll fix this - should be easy to propogate!

**Comment by SM-Figueroa** [comment]
Hi @TomDonoghue. I'm an undergraduate researcher working with MJ. I've already started on a fix for this issue and would be happy to open a pull request in the near future. Please let me know if that's acceptable. Thanks.

**Comment by TomDonoghue** [comment]
@SM-Figueroa - thanks for the interest! Apologies, I only saw this message after I'd already gone ahead and done the updates in #293, so there is already some stuff related to this in progress. 

I had a look at your branch and I like what you are doing with `set_run_modes` and so on, I think it's a nice and clean implementation. Can you open a PR with what you have, and I can help merge what you've added that is beyond #293?

**Comment by TomDonoghue** [comment]
This is now addressed in #293 - so moving discussion over there and closing this here now
