### ISSUE TITLE
bug report: AttributeError: 'FOOOF' object has no attribute 'to_df'

### ISSUE THREAD

**Issue by sunh20** [fooof-tools/fooof#307]
I've been generating FOOOF and FOOOFGroup reports just fine using version 1.0.0, but the to_df() function hasn't been working for either object. I'm seeing that the get_results() method could be a temp workaround but would ideally have a nicely formatted df. 

I tried cloning the fooof repo and checking that the to_df() function is indeed present in the source code. 
I also ran the plot_data_exporting.ipynb notebook, which generated the same error. 

Any help would be appreciated!

**Comment by TomDonoghue** [comment]
Closing this since there are no action items - hopefully updating fooof worked for you @sunh20!
