### ISSUE TITLE
units/scaling for PW and min_peak _height? 

### ISSUE THREAD

**Issue by SusanL82** [fooof-tools/fooof#309]
Hello, 

I'm trying to fit my hippocampal LFP power spectra and I am getting some confusing results. 
When I have my `min_peak_height` set to 0.2, I obtain some peaks with a PW value lower than 0.2. I don't think that this should be possible. I think that this could be related to the issue described here #262 . 
I've attached an example here: [FOOOF_report_NREM_HD132-1008_pre_CTX_STSP_PowSpec_FOOOF.pdf](https://github.com/fooof-tools/fooof/files/13297141/FOOOF_report_NREM_HD132-1008_pre_CTX_STSP_PowSpec_FOOOF.pdf)

So, if I want to reduce overfitting (I think) by adjusting my min_peak_value values (in other spectra than the attached one, which looks fine). If I want to guess at a suitable value for `min_peak_value` based on the graphs in the fooof report, and my noise seems to be smaller than 0.3 above background, should I try to set `min_peak_value` to 10^0.3? Or to 0.3?

And just to make sure: does this mean that PW is listed as log(Power)? Looking at the graph in the fooof report, this seems to be the case. 

Thanks for your help, 
Susan

**Comment by TomDonoghue** [comment]
This is described in the tutorials - the min peak height is a threshold for peak detection, but there is a subsequent re-fitting process, so peaks are not guaranteed to surpass this value:
https://fooof-tools.github.io/fooof/auto_tutorials/plot_04-MoreFOOOF.html

**Comment by SusanL82** [comment]
Oops, I hadn't looked at the tutorials for a while...  I guess it's just a coincidence that I haven't had those smaller peaks show up in my recordings until now. Thanks for the clarification! 

Now I just need to figure out what to do about those slightly asymmetrical peaks that get two largely overlapping gaussians, but that's a very different kind of problem to solve (and maybe a new issue eventually).

**Comment by TomDonoghue** [comment]
@SusanL82 - there is an upcoming major update to the module, which will have alternate fit functions for the peaks, including a skewed gaussian - which might perform better in cases with asymmetric peaks!
