### ISSUE TITLE
[Question] ERROR regarding Lower-bound peak width limit is < or ~= the frequency resolution: 1.00 <= 1.00

### ISSUE THREAD

**Issue by stellafychang** [fooof-tools/fooof#317]
I got an error when I tried to do group fitting. Below is the error

> 
> FOOOF WARNING: Lower-bound peak width limit is < or ~= the frequency resolution: 1.00 <= 1.00
> 	Lower bounds below frequency-resolution have no effect (effective lower bound is the frequency resolution).
> 	Too low a limit may lead to overfitting noise as small bandwidth peaks.
> 	We recommend a lower bound of approximately 2x the frequency resolution.
> 
> 

My question is how to fix the error? I was thinking of re-extracting psd again with different parameters, but was not sure which approach is most appropriate. Or do I miss anything? 

Below is the code for extracting psd

```
EEG.srate = 250; %EEG sampling rate was at 250 Hz
WINDOW = EEG.srate;
NFFT = EEG.srate;
[psd, freqs] = pwelch(epochChannelData(:,:,epoch_idx), WINDOW, [], NFFT, EEG.srate); 
```

**Comment by TomDonoghue** [comment]
Hey @stellafychang - this isn't an error, it's a warning noting that your selected lower bound peak width limit doesn't work very well with your PSD's frequency resolution.

For more information on the settings, see the 
[tutorials](https://fooof-tools.github.io/fooof/auto_tutorials/index.html), in particular, this one:
https://fooof-tools.github.io/fooof/auto_tutorials/plot_04-MoreFOOOF.html

The model still fits if this model is printed. If you wish to address the warning, you can either change the peak width limits, or recompute your power spectrum with a different (higher) frequency resolution.

**Comment by TomDonoghue** [comment]
Since there isn't an action item here, I'm going to close this issue now. @stellafychang - if you have any questions or follow ups, feel free to add them here and we can follow up from there!
