### ISSUE TITLE
spectparam calculates the slope for Nyquist regardless of the freq-range

### ISSUE THREAD

**Issue by mayucel** [fooof-tools/fooof#336]
My nyquist is 2.5.
So if I type in 
# Import the model object
from specparam import SpectralModel

# Initialize model object
fm = SpectralModel()

# Define frequency range across which to model the spectrum
freq_range = [0.01, 1]

# Model the power spectrum with FOOOF, and print out a report
fm.report(freq, psdx, freq_range)

It still plots and fits until 2.5Hz instead of 1.

**Comment by TomDonoghue** [comment]
This is the same issue as #327 - please check the issues board before opening a new issue. 

This issue has been fixed - you can install the version from Github to get the fix

**Comment by mayucel** [comment]
Thanks!
