### ISSUE TITLE
bg_guess

### ISSUE THREAD

**Issue by voytek** [fooof-tools/fooof#82]
Now that some folks are using it, I'm a bit unhappy with my decision to set the default bg_guess for the slope parameter to 2.

We should consider moving it to be the slope between the first and last points, for example. This moves it away from "neural PSD assumption" to "data-driven assumption" that's more agnostic to the source.

This come specifically from a conversation I'm having with someone who's running this on coherence spectra, instead of power spectra, where the -2 slope assumption may not hold.

**Comment by TomDonoghue** [comment]
I'm not sure bg_guess actually matters that much. It's a seed value, sure, but my intuition from explorations is that it doesn't have all that influence on the final result. 

Maybe I'm wrong about that - we could first check it's influence - but it's not clear there is any other better value. 

Maybe this suggests it could be more explicitly user set-able, which is an option,  but also this parameter should be (implicitly) pretty updatable, for users doing "weirder" things (like fitting coherence spectra):

```
fm = FOOOF()
fm._bg_guess[2] = new_value
```

**Comment by voytek** [comment]
Sure, it may very well not matter since it's just a seed.

I'm more just concerned that it's one of our last "magic number" numbers, in that it's hard set rather than data driven.

I think the better solution is the one I proposed: simple estimate of slope from the delta between the first and last <x,y> values.

**Comment by voytek** [comment]
Just like how we estimate offset from the first value.

**Comment by TomDonoghue** [comment]
I'll check what influence that switch would have - I have a feeling it's perhaps not a big shift, in which case, yeh, data-driven removes a magic number. 

However: my worry is that that data-driven estimate will be a little volatile (first & last point are often least representative), and the premise of what it's trying to estimate doesn't really make sense in the knee-fit case.

**Comment by voytek** [comment]
Fair. But magic numbers, Tom! EW.

**Comment by TomDonoghue** [comment]
Agreed - but it's not *completely* magic. It's an empirical check from here -  I'll report back.

**Comment by parenthetical-e** [comment]
Brad's spot on.

**Comment by TomDonoghue** [comment]
So, it turns out it makes absolutely no difference to any test runs I do whether the guess exponent is set at two, or data derived. To get rid of a magic number, it has been updated to use the data derived value (in #152). Closing this - reopen if anyone wants to bring anything up about it.
