### ISSUE TITLE
Explore gamma function fitting as alternative to gaussian fitting

### ISSUE THREAD

**Issue by voytek** [fooof-tools/fooof#85]
There are some cases where there's a peak with a long right tail that fooof will fit 2-3 gaussians to, when this may not match human intuition for what's happening.

Granted we do not currently know what the ground truth is in these situations, but it's worth exploring how fitting a gamma function, rather than a gaussian, might achieve similar overall fit performance with fewer parameters, matching more how human raters seem to fit.

**Comment by TomDonoghue** [comment]
Following #154, this has been moved to:
fooof-tools/Dev-Ideas#4
