### ISSUE TITLE
Turn the jupyter notebooks into docs and serve 'em with sphinx gallery!

### ISSUE THREAD

**Issue by choldgraf** [fooof-tools/fooof#9]
This looks cool! @voytek it's basically the method you were working on with Matar, right?

I noticed you've got a bunch of demo-style notebooks in the root level of the repo. I think it'd be helpful if these were python files that were served with sphinx. What do you all think about this? (happy to help set that up if there's interest)

as an example, here's the MNE examples folder: https://github.com/mne-tools/mne-python/tree/master/examples

and this gets turned into this gallery:

http://martinos.org/mne/stable/auto_examples/index.html

with each example getting notebook-ified:

http://martinos.org/mne/dev/auto_examples/decoding/plot_receptive_field.html#sphx-glr-auto-examples-decoding-plot-receptive-field-py

**Comment by TomDonoghue** [comment]
Hey @choldgraf so, only about a literal year later - this is actually happening!

I have a couple quick questions, that I think you might be best to answer, if you have a second!
- I see there is at least some support for using Binder with Sphinx. If we totally port our current notebooks to sphinx-examples, do you think the Binder support is mature enough to add a Binder link to them, through Sphinx-gallery (note: we are using Github pages). 
- Do you see any issue with having two Sphinx-Galleries on the same website? I'm thinking an explicit 'tutorial' section, as well as a separate collection of 'examples'. 

The potential other option, related to both these questions, is to actually keep the 'tutorial' folder as is [notebooks, with Binder], and to separately populate the sphinx-gallery with actual examples.

**Comment by choldgraf** [comment]
Yo!

For your two bullet points:

 > do you think the Binder support is mature enough to add a Binder link to them, through Sphinx-gallery

Binder has been super stable over the last several months, so in general I think yes! One main caveat is to remember that the resources available to Binder users are pretty small (we gotta do this to be able to afford offering a gigantic amount of free compute to people). So make sure your examples don't use too much (RAM, in particular)

> Do you see any issue with having two Sphinx-Galleries on the same website? 

Nope, in fact [there is a section on this in the docs](https://sphinx-gallery.readthedocs.io/en/latest/configuration.html#multiple-galleries-config)!

Could you take a look at the sphinx-gallery docs (https://sphinx-gallery.readthedocs.io) and give me feedback about anything that is confusing / doesn't make sense / etc? I'm trying to make a few rounds improving the documentation but it's quite hard to do so when you already know how the project works!

I'm gonna be slow to respond for the next week or two because I'm on my honeymoon :-) but you've caught me

**Comment by TomDonoghue** [comment]
@choldgraf : huge thanks for the answers, but I'm so sorry - I did not mean to interrupt your honeymoon! (Congratulations, by the way!)

This will help me work through finishing adding Sphinx, and I'll collect thoughts / comments on the documentation for sphinx-gallery as I go - and get back to you with them (and perhaps any more questions) in a couple weeks, when you are back! Thanks!

**Comment by TomDonoghue** [comment]
Some ToDos / clean ups left in, mentioned in #94, but sphinx is now deployed
