### ISSUE TITLE
Undefined behavior when simulating power spectrum

### ISSUE THREAD

**Issue by ArcadeShrimp** [fooof-tools/fooof#92]
Power spectra are created from gen_power_spectrum( ) and gen_group_power_spectra( ) even though the 'central frequency' from the passed 'gauss_params' is outside the passed in 'freq_range.'

After some tests it seems that freq_range acts more as a display window rather than a generation range. This means central frequencies can be added regardless of the given frequency range. Is this the intended design?

![screenshot 4](https://user-images.githubusercontent.com/14008089/44545008-b24f1f80-a6c8-11e8-8748-a72a2a12c625.png)
![screenshot 5](https://user-images.githubusercontent.com/14008089/44545009-b24f1f80-a6c8-11e8-8fb3-487f6f6adeaa.png)
![screenshot 7](https://user-images.githubusercontent.com/14008089/44640277-a5a32380-a975-11e8-858e-591f55f98dc9.png)

**Comment by TomDonoghue** [comment]
Hmm. I'm looking into this now, and it is sorta weird for it to work like this, but I'm also not entirely sure I want to stop it doing this. 

Doing so would require setting some arbitrary limit on error-ing out if peak definition were too close to the edge. 

This would then preclude generating data to, for example, test the impact of having peaks at the edge (though one could generate with a broader range and restrict when fitting). 

Maybe makes more sense to print a warning if peaks are out of range, or close to it? I'll come back to this one - not the most important thing.

**Comment by TomDonoghue** [comment]
Okay @ArcadeShrimp : thank you for catching this, and bringing it up!

As I mentioned above, I don't want to be heavy-handed on restricting this from happening, as it could be useful in same cases, and is hopefully not too common that people end up doing it by accident. I thought about adding a warning, but there is currently no print outs from these functions, and it's a fair amount of annoying code to add the checks and printed warnings, and then also only print once in the case of simulating a group, etc, so for now I've opted for the simpler approach of just adding a small note in the docstrings - hopefully that covers it. We'll leave it like this for now - we can revisit / update if it seems to become an issue.
